<?php

namespace app\controllers;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;
use app\models\RoleUser;

class AdminController extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    //    public function behaviors()
    //    {
//        return [
//            'access' => [
//                'class' => AccessControl::className(),
//                'only' => ['logout'],
//                'rules' => [
//                    [
//                        'actions' => ['admin/logout'],
//                        'allow' => true,
//                        'roles' => ['@'],
//                    ],
//                ],
//            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'logout' => ['post'],
//                ],
//            ],
//        ];
//    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout='@app/views/adminlayouts/main.php';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $session = Yii::$app->session;
        if($session->has("admin")&&$session->get('role')==1){
            return $this->render('index');
        }else{
            return $this->redirect('login');
        }

    }

    public function actionLogin(){
        $session = Yii::$app->session;
        if($session->has("admin")&&$session->get('role')==1){
           return $this->redirect('index');
        }else{
             $model = new LoginForm();
            if ($model->load(Yii::$app->request->post()) && $model->login()) {
                return $this->redirect('index');
            }

            $model->password = '';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout(){
//        Yii::$app->user->logout();
        $session = Yii::$app->session;
        $session->removeAll();
        return $this->redirect('login');
    }

}
